[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
maxUploadSize = 10

[runner]
fastReruns = false
enforceSerializableSessionState = false

[client]
toolbarMode = "minimal"
showErrorDetails = false


[theme]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#0d2a6e"
textColor = "#000000"
