[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"
maxUploadSize = 50

[runner]
fastReruns = false
enforceSerializableSessionState = false

[client]
toolbarMode = "minimal"
showErrorDetails = false


[theme]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#0d2a6e"
textColor = "#000000"
